export interface CatalogueService {
  name: string;
  price: string;
  badge?: string;
  desc?: string;
}

export interface CatalogueCategory {
  id: string;
  title: string;
  subtitle: string;
  iconName: string;
  services: CatalogueService[];
}

export interface MonthlyPackage {
  name: string;
  price: string;
  popular?: boolean;
  features: string[];
  ctaText: string;
}

export const MONTHLY_PACKAGES: MonthlyPackage[] = [
  {
    name: "Basic Retainer",
    price: "₹15,000 / month",
    features: [
      "30 Social Media Creatives",
      "8 Custom Reels / Short Videos",
      "Complete Social Media Management",
      "Monthly Content Calendar",
      "Performance Analytics Report",
    ],
    ctaText: "Choose Basic Plan",
  },
  {
    name: "Standard Retainer",
    price: "₹25,000 / month",
    popular: true,
    features: [
      "40 Social Media Creatives",
      "12 Custom Reels / Short Videos",
      "Meta Ads Campaign Management",
      "On-Page & Local SEO",
      "WhatsApp Marketing Broadcasts",
      "Dedicated Account Manager",
    ],
    ctaText: "Choose Standard Plan",
  },
  {
    name: "Premium Enterprise",
    price: "₹50,000 / month",
    features: [
      "Unlimited Social Creatives",
      "20 High-Production Reels",
      "Meta & Google Ads Management",
      "Full SEO & Technical Optimization",
      "Website Maintenance & Updates",
      "B2B & B2C Lead Generation",
      "Weekly Strategy Meetings",
    ],
    ctaText: "Choose Premium Plan",
  },
];

export const FULL_CATALOGUE_DATA: CatalogueCategory[] = [
  {
    id: "business-registration",
    title: "1. Business Registration & Legal Services",
    subtitle: "Compliance, licensing, government approvals & legal formations",
    iconName: "ShieldCheck",
    services: [
      { name: "MSME (Udyam) Registration", price: "₹2,000" },
      { name: "GST Registration", price: "₹2,500" },
      { name: "PAN & TAN Registration", price: "₹2,000" },
      { name: "FSSAI Registration / License", price: "₹3,500" },
      { name: "Shop & Establishment Registration", price: "₹3,000" },
      { name: "Trade License", price: "₹5,000" },
      { name: "Professional Tax Registration", price: "₹3,000" },
      { name: "EPF & ESI Registration", price: "₹5,000" },
      { name: "Import Export Code (IEC)", price: "₹4,000" },
      { name: "Digital Signature Certificate (DSC)", price: "₹3,500" },
      { name: "LLP Registration", price: "₹25,000 onwards" },
      { name: "Private Limited Company Registration", price: "₹35,000 onwards", badge: "POPULAR" },
      { name: "OPC (One Person Company) Registration", price: "₹30,000 onwards" },
      { name: "Partnership Firm Registration", price: "₹10,000 onwards" },
      { name: "Trust Registration", price: "₹20,000 onwards" },
      { name: "Society Registration", price: "₹20,000 onwards" },
      { name: "Section 8 Company Registration", price: "₹35,000 onwards" },
      { name: "Trademark Registration", price: "₹8,000 onwards", badge: "RECOMMENDED" },
      { name: "Copyright Registration", price: "₹8,000 onwards" },
      { name: "Patent Filing Assistance", price: "₹25,000 onwards" },
      { name: "ISO Certification", price: "₹8,000 onwards" },
      { name: "Startup India Registration", price: "₹5,000 onwards" },
      { name: "GeM Registration", price: "₹5,000 onwards" },
      { name: "Tender Registration & Documentation", price: "₹10,000 onwards" },
      { name: "Fire NOC Assistance", price: "Custom Quote" },
      { name: "Pollution Control License Assistance", price: "Custom Quote" },
      { name: "Factory License Assistance", price: "₹10,000 onwards" },
      { name: "Labour License Assistance", price: "₹8,000 onwards" },
    ],
  },
  {
    id: "web-tech",
    title: "2. Website, Apps & Technology Solutions",
    subtitle: "Modern Next.js web applications, mobile apps, software & AI integrations",
    iconName: "Globe",
    services: [
      { name: "Portfolio Website", price: "₹3,999" },
      { name: "Landing Page Website", price: "₹4,999", badge: "HIGH CONVERSION" },
      { name: "Business Website", price: "₹9,999" },
      { name: "Corporate Website", price: "₹19,999", badge: "POPULAR" },
      { name: "E-Commerce Store (Shopify/Next.js)", price: "₹24,999" },
      { name: "Custom Web Application", price: "₹49,999" },
      { name: "Customer Portal / Dashboard", price: "₹29,999" },
      { name: "Learning Management System (LMS)", price: "₹79,999" },
      { name: "ERP / CRM Solution", price: "₹99,999" },
      { name: "SaaS Platform Development", price: "₹1,49,999" },
      { name: "Android Mobile Application", price: "₹39,999" },
      { name: "iOS Mobile Application", price: "₹59,999" },
      { name: "Cross-Platform Mobile App (Flutter/React Native)", price: "₹79,999" },
      { name: "Enterprise Mobile Solution", price: "₹1,49,999" },
      { name: "AI Chatbot Integration", price: "₹14,999", badge: "HOT AI" },
      { name: "AI Workflow Automation", price: "₹24,999" },
      { name: "Custom AI Solutions", price: "₹49,999" },
      { name: "Billing & POS System", price: "₹39,999" },
      { name: "Hospital / School Management System", price: "₹79,999 onwards" },
      { name: "HR & Payroll System", price: "₹79,999" },
      { name: "Appointment Booking System", price: "₹24,999" },
      { name: "Cloud Deployment & Server Setup", price: "₹9,999" },
      { name: "REST API & Payment Gateway Integration", price: "₹4,999 onwards" },
      { name: "WhatsApp API Integration", price: "₹14,999" },
      { name: "Cyber Security Audit & Pen Testing", price: "₹14,999 onwards" },
      { name: "Website Maintenance", price: "₹999 / month" },
    ],
  },
  {
    id: "digital-marketing",
    title: "3. Digital Marketing & Performance Ads",
    subtitle: "High-ROI Facebook, Instagram, Google, LinkedIn & OTT advertising",
    iconName: "TrendingUp",
    services: [
      { name: "Social Media Management", price: "₹15,000 / month", badge: "POPULAR" },
      { name: "Social Media Handling", price: "₹8,000 / month" },
      { name: "Meta Ads Management (FB & Insta)", price: "₹5,000 / month" },
      { name: "Google Ads Management (Search/Display)", price: "₹7,500 / month" },
      { name: "SEO (Search Engine Optimization)", price: "₹10,000 / month" },
      { name: "Local SEO & Google Business", price: "₹5,000 / month" },
      { name: "WhatsApp Marketing Campaigns", price: "₹3,000 onwards" },
      { name: "Email & SMS Marketing", price: "₹2,500 onwards" },
      { name: "Content Marketing", price: "₹5,000 / month" },
      { name: "Qualified Lead Generation Engine", price: "₹8,000 onwards", badge: "HIGH ROI" },
      { name: "YouTube & LinkedIn Marketing", price: "₹8,000 / month" },
      { name: "Meta Pixel & Conversion API Setup", price: "₹5,000" },
      { name: "Google Analytics (GA4) & GTM Setup", price: "₹5,000" },
      { name: "Dynamic Product Ads & Remarketing", price: "₹15,000 / month" },
      { name: "OTT Ads (Disney+ Hotstar, SonyLIV, Zee5)", price: "₹30,000 / month" },
      { name: "Audio Ads (Spotify, JioSaavn, Gaana)", price: "₹20,000 / month" },
      { name: "Performance Marketing Retainer - Growth", price: "₹20,000 / month" },
      { name: "Performance Marketing Retainer - Enterprise", price: "₹50,000 / month" },
    ],
  },
  {
    id: "branding-design",
    title: "4. Branding & Graphic Design",
    subtitle: "Cinematic visual identities, logo design, print & digital collateral",
    iconName: "Palette",
    services: [
      { name: "Logo Design", price: "₹999 / ₹3,000", badge: "BEST SELLER" },
      { name: "Brand Identity Suite", price: "₹10,000", badge: "POPULAR" },
      { name: "Company Profile Design", price: "₹7,500" },
      { name: "Brochure Design", price: "₹3,500" },
      { name: "Catalogue Design", price: "₹5,000" },
      { name: "Packaging & Label Design", price: "₹5,000" },
      { name: "Business Card Design", price: "₹1,000" },
      { name: "Letterhead & Invoice Design", price: "₹800" },
      { name: "Social Media Poster", price: "₹500" },
      { name: "Premium Creative Poster", price: "₹1,000" },
      { name: "Banner / Flex Artwork Design", price: "₹1,500" },
      { name: "Pitch Deck Presentation Design", price: "₹3,000" },
      { name: "Restaurant Menu Design", price: "₹2,000" },
      { name: "Event Invitation Design", price: "₹1,500" },
    ],
  },
  {
    id: "video-photography",
    title: "5. Video Production & Photography",
    subtitle: "Reels, commercial videos, 3D motion graphics & studio shoots",
    iconName: "Video",
    services: [
      { name: "Reel Editing", price: "₹800 / video" },
      { name: "Premium Commercial Reel", price: "₹1,500 / video", badge: "TRENDING" },
      { name: "YouTube Video Editing", price: "₹2,500 / video" },
      { name: "Corporate Brand Video", price: "₹5,000 onwards" },
      { name: "Motion Graphics & 2D/3D Animations", price: "₹6,000 onwards" },
      { name: "Promotional Product Video", price: "₹4,000 onwards" },
      { name: "YouTube Thumbnail Design", price: "₹500" },
      { name: "Studio Product Photography", price: "₹5,000" },
      { name: "Corporate Photography", price: "₹8,000" },
      { name: "Event & Conference Photography", price: "₹10,000" },
      { name: "Food & Culinary Photography", price: "₹5,000" },
      { name: "Real Estate Property Photography", price: "₹10,000" },
    ],
  },
  {
    id: "events-printing",
    title: "6. Event Management & Printing Solutions",
    subtitle: "Turnkey corporate events, launches & high-grade physical print production",
    iconName: "Award",
    services: [
      { name: "School / College Event Management", price: "₹20,000 onwards" },
      { name: "Corporate Event Management", price: "₹50,000 onwards" },
      { name: "Product Launch Event", price: "₹75,000" },
      { name: "Brand Activation Campaign", price: "₹1,00,000" },
      { name: "Conferences & Award Functions", price: "₹50,000 onwards" },
      { name: "Exhibition Stall Management", price: "₹50,000" },
      { name: "Celebrity & Influencer Management", price: "Custom Quote" },
      { name: "Visiting Cards Printing", price: "₹500" },
      { name: "Flyers Printing", price: "₹2,000" },
      { name: "Brochures & Catalogues Printing", price: "₹3,000" },
      { name: "Stickers & Label Printing", price: "₹1,500" },
      { name: "Flex Printing", price: "₹15 / sq.ft" },
      { name: "Sign Boards & LED Displays", price: "Custom Quote" },
      { name: "ID Cards & Certificates Printing", price: "₹100 / card" },
      { name: "Corporate Gift Stationery", price: "Custom Quote" },
      { name: "Offline Advertising (Billboards, Bus, Metro)", price: "₹25,000 onwards" },
    ],
  },
  {
    id: "consulting-innovation",
    title: "7. Business Consulting, Startup & Innovation",
    subtitle: "Strategy, startup mentorship, financial projections, SOPs & ideation",
    iconName: "Briefcase",
    services: [
      { name: "Business Consultation", price: "₹2,000 / hour" },
      { name: "Startup Consultation", price: "₹5,000" },
      { name: "Startup Idea Validation", price: "₹10,000" },
      { name: "Marketing & Sales Strategy", price: "₹7,500" },
      { name: "Business Growth & Expansion Plan", price: "₹10,000" },
      { name: "Business Model Development", price: "₹15,000" },
      { name: "Brand Positioning & Market Research", price: "₹10,000" },
      { name: "Investor Pitch Deck Design", price: "₹15,000", badge: "HIGH DEMAND" },
      { name: "Financial Projection Modeling", price: "₹15,000" },
      { name: "Go-To-Market Strategy", price: "₹20,000" },
      { name: "Franchise Development Planning", price: "₹25,000" },
      { name: "Digital Transformation & Automation", price: "₹20,000" },
      { name: "SOP Development", price: "₹20,000" },
      { name: "CRM & Sales Funnel Architecture", price: "₹20,000" },
      { name: "Team Training Session", price: "₹10,000 / session" },
      { name: "Full Business Health Audit", price: "₹15,000" },
      { name: "AI Business Integration Consulting", price: "₹20,000", badge: "AI FUTURE" },
      { name: "Entrepreneur Mentorship", price: "₹5,000 / session" },
    ],
  },
];
